/**
 * Auto-generated by scripts/write-ssr-asset-map.mjs — do not edit.
 */
export const ssrAssetHashes = {
  "nightlife": {
    "js": "/assets/nightlife-t8K1LklQ.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/nightlife-DyqvxUsY.css"
    ]
  },
  "clubDetail": {
    "js": "/assets/clubDetail-CloWeN6c.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/venue-request-modal-Dcpx4a3a.css",
      "/assets/clubDetail-CkqTDZHG.css"
    ]
  }
} as const;
