/**
 * Auto-generated by scripts/write-ssr-asset-map.mjs — do not edit.
 */
export const ssrAssetHashes = {
  "nightlife": {
    "js": "/assets/nightlife-C1g5sPMr.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/nightlife-BiowZzvT.css"
    ]
  },
  "clubDetail": {
    "js": "/assets/clubDetail-C1Jdjngg.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/venue-request-modal-Dcpx4a3a.css",
      "/assets/clubDetail-BCv0bnLc.css"
    ]
  }
} as const;
