/**
 * Auto-generated by scripts/write-ssr-asset-map.mjs — do not edit.
 */
export const ssrAssetHashes = {
  "nightlife": {
    "js": "/assets/nightlife-taCEXoTh.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/nightlife-DyqvxUsY.css"
    ]
  },
  "clubDetail": {
    "js": "/assets/clubDetail-D6qaw4lN.js",
    "css": [
      "/assets/chrome-6Hokc4zM.css",
      "/assets/venue-request-modal-Dcpx4a3a.css",
      "/assets/clubDetail-CK0Y5p_c.css"
    ]
  }
} as const;
